version: 3

repositories:
  - _comment: .gitconfig (Linux x64 profile)
    url: https://raw.githubusercontent.com/pirakansa/bootkit/main/assets/
    files:
      - file_name: gitconfig
        rename: .gitconfig
        out_dir: $HOME

  - _comment: .vimrc (Linux x64 profile)
    url: https://raw.githubusercontent.com/pirakansa/bootkit/main/assets/
    files:
      - file_name: vimrc
        rename: .vimrc
        out_dir: $HOME

  - _comment: VS Code settings.json (Linux x64 profile)
    url: https://raw.githubusercontent.com/pirakansa/bootkit/main/assets/
    files:
      - file_name: vscode-settings.json
        rename: settings.json
        out_dir: $HOME/.config/Code/User
