version: 1

repositories:
  - _comment: GitHub Copilot CLI (Linux x64)
    url: https://github.com/github/copilot-cli/releases/download/v0.0.422/
    files:
      - file_name: copilot-linux-x64.tar.gz
        encoding: tar+gzip
        extract: copilot
        rename: copilot
        out_dir: $HOME/.local/bin
        mode: "0755"
