version: 3

repositories:
  - _comment: GitHub CLI (Linux x64)
    url: https://github.com/cli/cli/releases/download/v2.87.2/
    files:
      - file_name: gh_2.87.2_linux_amd64.tar.gz
        encoding: tar+gzip
        extract: gh_2.87.2_linux_amd64/bin/gh
        rename: gh
        out_dir: $HOME/.local/bin
        mode: "0755"
