version: 1

repositories:
  - _comment: Node.js (Linux x64)
    url: https://nodejs.org/dist/v24.13.1/
    files:
      - file_name: node-v24.13.1-linux-x64.tar.xz
        encoding: tar+xz
        extract: node-v24.13.1-linux-x64
        out_dir: $HOME/.local/lib/node
