version: 1

vars:
  NODEJS_VERSION: "26.4.0"

repositories:
  - _comment: Node.js (Linux x64)
    url: https://nodejs.org/dist/v${{ .vars.NODEJS_VERSION }}
    files:
      - file_name: node-v${{ .vars.NODEJS_VERSION }}-linux-x64.tar.xz
        encoding: tar+xz
        extract: node-v${{ .vars.NODEJS_VERSION }}-linux-x64
        out_dir: $HOME/.local/lib/node
