version: 1

vars:
  OPENCODE_VERSION: "1.4.3"

repositories:
  - _comment: OpenCode (Linux x64)
    url: https://github.com/anomalyco/opencode/releases/download/v${{ .vars.OPENCODE_VERSION }}
    files:
      - file_name: opencode-linux-x64.tar.gz
        encoding: tar+gzip
        extract: opencode
        rename: opencode
        out_dir: $HOME/.local/bin
        mode: "0755"
