version: 1

repositories:
  - _comment: VS Code settings.json
    url: https://raw.githubusercontent.com/pirakansa/bootkit/main/assets/
    files:
      - file_name: vscode-settings.json
        rename: settings.json
        out_dir: $HOME/.config/Code/User
